In [1]:
import pandas as pd

In [2]:
read_csv = pd.read_csv("c:/users/musfik/documents/Copy of Fortune_10.csv")
read_csv

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Date,Date Time
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%,Yes,1/2/2024
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%,Yes,1/3/2024
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%,Yes,1/4/2024
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%,Yes,1/5/2024
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%,Yes,NaN
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%,No,NaN
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%,Yes,NaN
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%,Yes,NaN
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%,No,NaN
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%,Yes,NaN

In [3]:
read_csv.interpolate()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Date,Date Time
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%,Yes,1/2/2024
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%,Yes,1/3/2024
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%,Yes,1/4/2024
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%,Yes,1/5/2024
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%,Yes,NaN
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%,No,NaN
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%,Yes,NaN
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%,Yes,NaN
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%,No,NaN
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%,Yes,NaN

In [4]:
read_csv.interpolate(method="time")

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Date,Date Time
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%,Yes,1/2/2024
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%,Yes,1/3/2024
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%,Yes,1/4/2024
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%,Yes,1/5/2024
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%,Yes,NaN
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%,No,NaN
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%,Yes,NaN
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%,Yes,NaN
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%,No,NaN
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%,Yes,NaN

In [17]:
read_csv = pd.read_csv("c:/users/musfik/documents/Copy of Fortune_10.csv",parse_dates=["Date Time"],index_col="dateTime")
read_csv

ValueError: 'Date Time' is not in list

In [11]:
read_csv.interpolate()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Date
Date Time,,,,,,,,,
2024-01-02,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%,Yes
2024-01-03,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%,Yes
2024-01-04,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%,Yes
2024-01-05,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%,Yes
NaT,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%,Yes
NaT,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%,No
NaT,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%,Yes
2024-01-09,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%,Yes
2024-01-10,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%,No
2024-01-11,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%,Yes

KeyError: 'Date Time[0]'