In [1]:
import pandas as pd

In [4]:
read_csv = pd.read_csv("c:/users/musfik/documents/Copy of Fortune_10.csv")
read_csv

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Date
0,1,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553,30%,Yes
1,2,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916,20%,Yes
2,3,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820,7%,Yes
3,4,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557,26%,Yes
4,5,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627,8%,NaN
5,6,Techline,Health,2006.0,"$13,898,119","5,470,303 Dollars",8427816,23%,No
6,7,NaN,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116,NaN,Yes
7,8,Kayelectronics,NaN,2009.0,"$9,451,943",NaN,5573830,4%,Yes
8,9,Ganzlax,IT Services,2011.0,NaN,"3,878,113 Dollars",11901180,18%,No
9,10,Trantraxlax,Government Services,NaN,"$11,088,336","5,635,276 Dollars",5453060,7%,Yes

In [5]:
read_csv.fillna(0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Date
0,1,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553,30%,Yes
1,2,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916,20%,Yes
2,3,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820,7%,Yes
3,4,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557,26%,Yes
4,5,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627,8%,0
5,6,Techline,Health,2006.0,"$13,898,119","5,470,303 Dollars",8427816,23%,No
6,7,0,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116,0,Yes
7,8,Kayelectronics,0,2009.0,"$9,451,943",0,5573830,4%,Yes
8,9,Ganzlax,IT Services,2011.0,0,"3,878,113 Dollars",11901180,18%,No
9,10,Trantraxlax,Government Services,0.0,"$11,088,336","5,635,276 Dollars",5453060,7%,Yes

In [ ]:
read_csv.fillna(10)